version: '3'

services: 
 front:
  image: nginx:latest
  ports:
      - "80:80"
  volumes:
      - C:\Users\kevin\OneDrive\Documents\Ecole\M1\techno\testDoc\live2\dev\front:/usr/share/nginx/html
 back:
  build:
    context: dev/back/
    dockerfile: Dockerfile
  ports:
      - "3000:3000"
  volumes:
      - C:\Users\kevin\OneDrive\Documents\Ecole\M1\techno\testDoc\live2\dev\back:/usr/app
 mongodb:
  image: mongo:latest
  hostname: mongodb
  ports:
    - "27017:27017"